### ISSUE TITLE
More Information On How Bot Works

### ISSUE THREAD

**Issue by garinallstar** [lucxsm/assettobot#1]
I've managed to get the bot Online but have no clue what to do after using your / commands doesn't work could u please provide a more in-depth tutorial or video tutorial

**Comment by lucxsm** [comment]
If no slash command is working, then i think you forget to deploy the commands.

```cd src
node deploy_commands.js```

Then you can add with /serveradd a Embed. Do not forget to add the Channel there the Embed is in the config
